## YAML Template.
server:
    port: 7001

app:
    env: dev
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000

gcloud:
    project-id: tuel-test-dev
    
management:
    server:
        port: 9001
        